name: upload-nexus-mods

on:
  release:
    types: [ "published" ]

jobs:
  fetch-release:
    runs-on: ubuntu-latest
    steps:
      - name: Make Directory
        id: make_dir
        run: mkdir releases
      - name: Get Current Release
        id: get_current_release
        uses: KevinRohn/github-full-release-data@v2
        with:
          version: ${{ github.event.release.name }}
          asset-file: '*.zip'
          asset-output: './releases/'
      - name: Repack zipball to be inside BuffStackHUD folder
        run: |
          mkdir BuffStackHUD
          unzip './releases/*.zip' -d './BuffStackHUD'
          zip -r BuffStackHUD.zip BuffStackHUD
  upload-release:
    needs: ["fetch-release"]
    uses: BUTR/workflows/.github/workflows/release-nexusmods.yml@master
    with:
      nexusmods_game_id: warhammer40kdarktide
      nexusmods_mod_id: 470
      mod_filename: BuffStackHUD.zip
      mod_version: ${{ github.event.release.name }}
      mod_description: ${{ github.event.release.body }}
      artifact_name: BuffStackHUD.zip
    secrets:
      NEXUSMODS_APIKEY: ${{ secrets.NEXUSMODS_APIKEY }}
      NEXUSMODS_SESSION_COOKIE: ${{ secrets.NEXUSMODS_COOKIES }}
