name: upload-nexus-mods-manual

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'Tag of Release'
          required: true
          type: string
        cookie:
          required: true
          description: 'Cookie of logged in nexus mods session named nexusmods_session'
          type: string
        upload:
          required: true
          description: 'Actually upload the file'
          type: boolean

jobs:
  fetch-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current Release
        id: get_current_release
        uses: KevinRohn/github-full-release-data@v2
        with:
          version: ${{ github.event.inputs.version }}
    outputs:
      release-name: ${{ steps.get_current_release.outputs.name }}
      release-body: ${{fromJson(steps.get_current_release.outputs.body)}}
      release-tag: ${{ steps.get_current_release.outputs.tag_name }}
  fetch-upload:
    needs: ["fetch-release"]
    uses: bountygiver/DarktideModAutoUploader/.github/workflows/pack_mod.yml@v1
    with:
      nexusmods_mod_id: 470
      mod_version: ${{ needs.fetch-release.outputs.release-name }}
      mod_description: ${{ needs.fetch-release.outputs.release-body }}
      checkout_ref: ${{ needs.fetch-release.outputs.release-tag }}
    secrets:
      NEXUSMODS_APIKEY: ${{ secrets.NEXUSMODS_APIKEY }}
      NEXUSMODS_SESSION_COOKIE: ${{ inputs.cookie }}
