name: upload-nexus-mods

on:
  release:
    types: [ "published" ]


jobs:
  fetch-upload:
    uses: bountygiver/DarktideModAutoUploader/.github/workflows/pack_mod.yml@v4
    with:
      file_id: 1689616
      mod_version: ${{ github.event.release.name }}
      mod_description: ${{ github.event.release.body }}
      checkout_ref: ${{ github.event.release.tag_name }}
    secrets:
      NEXUSMODS_APIKEY: ${{ secrets.NEXUSMODS_APIKEY }}
